FROM ruby:3.1.3-bullseye 

ENV NODE_MAJOR=8 \
    RACK_ENV=development \
    RAILS_ENV=development

RUN apt-get update \
    && apt-get install -y apt-utils apt-transport-https curl netcat-openbsd

RUN curl -L https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor > /usr/share/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x bullseye main" > /etc/apt/sources.list.d/nodesource.list && \
    echo "deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x bullseye main" >> /etc/apt/sources.list.d/nodesource.list

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      # qt5-default
      zlib1g \
      zlib1g-dev \
      libffi-dev \
      libxml2-dev \
      libreadline-dev \
      libcurl4-openssl-dev \
      libpq-dev \
      libssl-dev \
      libsqlite3-dev \
      sqlite3 \
      nodejs \
      pkg-config \
      xauth \
      xvfb \
      build-essential \
      git \
      file \
      libqt5webkit5-dev \
      gstreamer1.0-plugins-base \
      gstreamer1.0-tools \
      gstreamer1.0-x

RUN gem update --system \
    && mkdir -p /app

WORKDIR /app

USER root
RUN echo "Package: *" > /etc/apt/preferences.d/01unstable && \
    echo "Pin: release a=sid" >> /etc/apt/preferences.d/01unstable && \
    echo "Pin-Priority: 400" >> /etc/apt/preferences.d/01unstable && \
    echo "deb https://deb.debian.org/debian sid main contrib non-free" >> /etc/apt/sources.list.d/unstable.list

RUN apt-get update && apt-get install -y -t unstable neovim lua-nvim lua-nvim-dev ruby-neovim python3-neovim ripgrep
RUN apt-get install -y tmux iproute2

RUN adduser --disabled-password --gecos=" " --uid 1000 user

RUN chown user:user -R /app
USER user
ENV BUNDLE_PATH=/home/user/.gems \
    GEM_HOME=/home/user/.gems  \
    BUNDLE_APP_CONFIG=/home/user/.gems \
    PATH=/home/user/.gems/bin:$PATH

RUN gem install bundler mailcatcher foreman
COPY Gemfile* /app/
RUN bundle install
ENTRYPOINT ["foreman", "start"]
USER root
RUN apt-get install -y vim-tiny iputils-ping iproute2 netcat-openbsd
USER user
