version: '2'
services:
  emmy:
    env_file:
      - ./env.development
    image: emmy-dev
    hostname: ruby
    command: bundle exec foreman start
    volumes:
      - .:/app/
    links:
      - redis
      - postgres
    ports:
      - '127.0.0.1:3000:3000'
      - '127.0.0.1:1080:1080'

  postgres:
    env_file:
      - ./env.development
    image: postgres:9.6
    hostname: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    env_file:
      - ./env.development
    image: redis:2.6
    hostname: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:
