version: '2'
services:
  emmy:
    env_file:
      - ./dot_env.development
    image: emmy-dev
    hostname: emmy
    #command: bundle exec foreman start
    # command: sh -c 'bundle exec foreman start'
    entrypoint: ['sh', '-c', 'while true ; do sleep 500 ; done']
    volumes:
      - .:/app/
      - ./_home:/home/user/
    ports:
      - '127.0.0.1:3000:3000'
      - '127.0.0.1:1080:1080'

  postgresql:
    env_file:
      - ./dot_env.development
    image: postgres:15.0
    hostname: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    image: redis:7-alpine
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'
    command: '--appendonly yes'

volumes:
  postgresql-data:
  redis-data:
