#!/bin/sh
exec 2>&1
DAEMON=mailcatcher
DAEMON_OPTS="-f --http-ip 0.0.0.0"
USER=nobody
GROUP=nogroup
echo "Booting mailcatcher"

echo "chpst -u $USER:$GROUP $DAEMON $DAEMON_OPTS"
exec chpst -u $USER:$GROUP $DAEMON $DAEMON_OPTS
